### PR TITLE
Improved visual design

### PR DESCRIPTION
**Pull request by mariofink**
I played around with some options and this is my first attempt at an improved visual design.
It is relying on react-canvas-knob for the rotary controls. While still far from perfect I think it can already be a step in the right direction. I also took the liberty of adding an editorconfig file and aligning the source code formatting.
Please review and share your feedback if you like.

### CODE REVIEW

**Comment by rolodato** [comment]
Thank you Mario, this is great! Much appreciated. It will be a while before I can review this, but rest assured I'll eventually get to it.

**Comment by mariofink** [comment]
Take your time – no need to hurry. 
It was a nice little project to get to know React a bit better. Having said that, I guess one of the next things I will do is to rewrite this in VueJS 😜

**Comment by rolodato** [comment]
Hi Mario, this looks great! I've been reviewing it and have a few comments.

It would be nice to have a fixed layout for large resolutions. For example, this is what the controls look like on my machine:

image

Something like this might be a bit easier to navigate:

image

That being said, it's not entirely clear exactly what the controls do (it wasn't clear either in my original version). For example, there are two controls named "EG INT" but there's way to know which is which.

I had considered adding the VCO, VCF, LFO and EG sections like on a real Volca, and seems this would make sense to have here as well. The closest we can get to a real Volca, the better.

Another thing that I noticed is that the scrolling seems to be backwards - I would expect scrolling up to increase a value and scrolling down to decrease it.

Finally, it would be nice to avoid values crossing from 127 to 0. Otherwise the controls feel like encoders, but they should be knobs instead.

Thanks again, and looking forward to your feedback!

**Comment by mariofink** [comment]
Hi Rodrigo,
thanks for your valuable feedback, I agree with all your points. 
However I will have to find some time to have a closer look.
Concerning the behaviour of the knobs, I am relying on a 3rd party plugin so I will have to see if that can be customised somehow to match your requirements.

Coming close to a real Volca Keys is a good approach. However while I was working on my own implementation based on VueJS I found out that you cannot control the Peak knob via MIDI – such a pity :(

**Comment by rolodato** [comment]
No problem - let me know if you're able to make those improvements :)

I noticed the peak knob is not controllable via MIDI as well, which is why it's not included as a parameter: https://github.com/rolodato/volca-keys-editor/blob/db79c162935cbc1a2b27da27c8331fe0c73109c0/src/index.jsx#L11.

Thanks again!

**Pull request closed without merging**
